import tiposDeSimbolos from "../../tipos-de-simbolos/css";

export default {
    'body': tiposDeSimbolos.TAG,
    'head': tiposDeSimbolos.TAG,
    'html': tiposDeSimbolos.TAG,
    'p': tiposDeSimbolos.TAG,
    'abbr': tiposDeSimbolos.TAG,
    'aside': tiposDeSimbolos.TAG,
    'area': tiposDeSimbolos.TAG,
    'textarea': tiposDeSimbolos.TAG,
    'article': tiposDeSimbolos.TAG,
    'q': tiposDeSimbolos.TAG,
    'audio': tiposDeSimbolos.TAG,
    'button': tiposDeSimbolos.TAG,
    'input': tiposDeSimbolos.TAG,
    'fieldset': tiposDeSimbolos.TAG,
    'canvas': tiposDeSimbolos.TAG,
    'td': tiposDeSimbolos.TAG,
    'blockquote': tiposDeSimbolos.TAG,
    'cite': tiposDeSimbolos.TAG,
    'code': tiposDeSimbolos.TAG,
    'col': tiposDeSimbolos.TAG,
    'tbody': tiposDeSimbolos.TAG,
    'dfn': tiposDeSimbolos.TAG,
    'details': tiposDeSimbolos.TAG,
    'div': tiposDeSimbolos.TAG,
    'address': tiposDeSimbolos.TAG,
    'span': tiposDeSimbolos.TAG,
    'slot': tiposDeSimbolos.TAG,
    'label': tiposDeSimbolos.TAG,
    'del': tiposDeSimbolos.TAG,
    'samp': tiposDeSimbolos.TAG,
    'form': tiposDeSimbolos.TAG,
    'colgroup': tiposDeSimbolos.TAG,
    'optgroup': tiposDeSimbolos.TAG,
    'hgroup': tiposDeSimbolos.TAG,
    'img': tiposDeSimbolos.TAG,
    'ins': tiposDeSimbolos.TAG,
    'template': tiposDeSimbolos.TAG,
    'em': tiposDeSimbolos.TAG,
    'li': tiposDeSimbolos.TAG,
}