export default {
    "abbr": ["abreviacao", "abreviação"],
    "aside": ["aparte"],
    "area": ["area", "área"],
    "textarea": ["area-texto", "área-texto"],
    "article": ["artigo"],
    "q": ["aspas"],
    "audio": ["audio", "áudio"],
    "button": ["botao", "botão"],
    "head": ["cabeca", "cabeça", "cabeca-tabela", "cabeça-tabela"],
    "input": ["campo"],
    "fieldset": ["campos"],
    "canvas": ["canvas"],
    "td": ["celula", "célula"],
    "blockquote": ["citacao", "citação"],
    "cite": ["citar"],
    "code": ["codigo", "código"],
    "col": ["coluna"],
    "body": "corpo",
    "tbody": "corpo-tabela",
    "dfn": ["definicao", "definição"],
    "details": ["detalhes"],
    "div": ["divisao", "divisão"],
    "address": ["endereco", "endereço"],
    "span": ["envelope-texto"],
    "label": ["etiqueta"],
    "del": ["excluido", "excluído"],
    "samp": ["exemplo"],
    "form": ["formulario", "formulário"],
    "colgroup": ["grupo-colunas", "grupo-opcoes"],
    "optgroup": ["grupo-opçoes", "grupo-opções"],
    "img": ["imagem"],
    "ins": ["inserido"],
    "template": ["invisivel", "invisível"],
    "em": ["italico", "itálico"],
    "li": ["item-lista"],
    "a": ["ligacao", "ligação"],
    "tr": ["linha"],
    "hr": ["linha-horizontal"],
    "dl": ["lista-definicoes", "lista-definições"],
    "dd": ["definicao", "definição"],
    "ol": ["lista-numerada"],
    "datalist": ["lista-pesquisavel", "lista-pesquisável"],
    "ul": ["lista-simples"],
    "html": ["lmht"],
    "mark": ["marca"],
    "meter": ["medidor"],
    "dialog": ["modal"],
    "nav": ["navegacao", "navegação"],
    "strong": ["negrito"],
    "object": ["objeto"],
    "option": ["opcao", "opção"],
    "p": ["p", "paragrafo", "parágrafo"],
    "pre": ["preformatado"],
    "main": ["principal"],
    "progress": ["progresso"],
    "br": ["quebra-linha"],
    "wbr": ["quebra-linha-oportuna"],
    "link": ["recurso"],
    "s": ["riscado"],
    "script": ["script"],
    "section": ["secao", "seção"],
    "select": ["selecao", "seleção"],
    "noscript": ["sem-script"],
    "sup": ["sobrescrito"],
    "u": ["sublinhado"],
    "sub": ["subscrito"],
    "summary": ["sumario", "sumário"],
    "table": ["tabela"],
    "kbd": ["teclado"],
    "time": ["tempo"],
    "dt": ["termo"],
    "small": ["texto-pequeno"],
    "h1": ["titulo1", "título1"],
    "h2": ["titulo2", "título2"],
    "h3": ["titulo3", "título3"],
    "h4": ["titulo4", "título4"],
    "h5": ["titulo5", "título5"],
    "h6": ["titulo6", "título6"],
    "var": ["variavel", "variável"]
}