export const Cores: { [indice: number]: string } = {
    0: 'cor-destaque',
    1: 'fundo',
    2: 'cor-fundo',
    3: 'cor-borda-em-bloco',
    4: 'cor-fim-borda-em-bloco',
    5: 'cor-inicio-borda-em-bloco',
    6: 'cor-início-borda-em-bloco',
    7: 'cor-borda-inferior',
    8: 'cor-borda',
    9: 'cor-borda-em-linha',
    10: 'cor-fim-borda-em-linha',
    11: 'cor-inicio-borda-em-linha',
    12: 'cor-início-borda-em-linha',
    13: 'cor-borda-esquerda',
    14: 'cor-borda-direita',
    15: 'cor-borda-superior',
    16: 'cor-cursor',
    17: 'cor',
    18: 'regras-cor-coluna',
    19: 'cor-contorno',
    20: 'cor-barra-rolagem',
    21: 'decoracao-cor-texto',
    22: 'decoração-cor-texto',
    23: 'cor-enfase-texto',
    24: 'cor-ênfase-texto',
}