export const PalavrasReservadas: Array<string> = [
    'velocidade-animacao',
    'velocidade-animação',
    'aparencia',
    'aparência',
    'filtro-fundo',
    'fundo',
    'fixar-fundo',
    'mesclar-fundo',
    'recortar-fundo',
    'origem-fundo',
    'repetir-fundo',
    'recolher-borda',
    // 'conteudo',
    // 'conteúdo',
    'incrementar-contador',
    'reiniciar-contador',
    'definir-contador',
    'cursor',
    'direcao',
    'direção',
    'fonte-texto',
    'estilo-fonte',
    'variacao-fonte',
    'variação-fonte',
    'variacao-fonte-alternativa',
    'variação-fonte-alternativa',
    'variacao-fonte-maiuscula',
    'variação-fonte-maiúscula',
    'variacao-fonte-asiatica',
    'variação-fonte-asiática',
    'variacao-fonte-ligacao',
    'variação-fonte-ligação',
    'variacao-fonte-numerica',
    'variação-fonte-numérica',
    'variacao-fonte-posicao',
    'variação-fonte-posição',
    'estilo-lista-tipo',
    'area-mascara',
    'área-máscara',
    'composicao-mascara',
    'composição-máscara',
    'modo-mascara',
    'modo-máscara',
    'origem-mascara',
    'origem-máscara',
    'repetir-mascara',
    'repetir-máscara',
    'modo-mescla',
    'ordem-pintura',
    'tipo-encaixe-rolagem-mouse',
    'enfase-texto',
    'ênfase-texto',
    'estilo-enfase-texto',
    'estilo-ênfase-texto',
    'orientacao-texto',
    'orientação-texto',
    'transformar',
    // 'nome-animacao',
    // 'nome-animação',
    'status-animacao',
    'status-animação',
    'visibilidade-fundo',
    'visibilidade',
];

export const FunçõesReservadas: Array<string> = [
    'recursos-fonte',
    'substituir-idioma-fonte',
    'configuracoes-variacao-fonte',
    'configurações-variação-fonte',
    'modelo-geral-em-grade',
    'modelo-colunas-em-grade',
    'modelo-linhas-em-grade',
]