export const Status: Array<string> = [
    'direcao-animacao',
    'direção-animação',
    'modo-preenchimento-animacao',
    'modo-preenchimento-animação',
    'nome-animacao',
    'nome-animação',
    'status-animacao',
    'status-animação',
    'aparencia',
    'aparência',
    'proporcao-tela',
    'proporção-tela',
    'visibilidade-fundo',
    'tamanho-em-bloco',
    'quebrar-apos',
    'quebrar-após',
    'quebrar-antes',
    'quebrar-dentro',
    'fluxo',
    'esquema-cor',
    'visibilidade-conteudo',
    'visibilidade-conteúdo',
    'flutuar',
    'espacamento-fonte',
    'espaçamento-fonte',
    'coluna-em-grade',
    'travar-pontuacao',
    'travar-pontuação',
    'hifens',
    'hífens',
    'isolamento',
    'deslocamento',
    'deslocamento-em-ancora',
    'deslocamento-em-âncora',
    'vazamento',
    'vazamento-em-ancora',
    'vazamento-em-âncora',
    'vazamento-em-bloco',
    'vazamento-em-linha',
    'vazamento-horizontal',
    'vazamento-vertical',
    'comportamento-rolagem-mouse',
    'comportamento-em-bloco-rolagem-mouse',
    'comportamento-em-linha-rolagem-mouse',
    'comportamento-horizontal-rolagem-mouse',
    'comportamento-vertical-rolagem-mouse',
    'quebrar-pagina-apos',
    'quebrar-página-após',
    'quebrar-pagina-antes',
    'quebrar-página-antes',
    'quebrar-pagina-dentro',
    'quebrar-página-dentro',
    'eventos-ponteiro',
    'aspas',
    'comportamento-rolagem',
    'calha-barra-rolagem',
    'largura-barra-rolagem',
    'design-tabela',
    'decoracao-texto-sublinhado',
    'decoração-texto-sublinhado',
    'justificar-texto',
    'renderizacao-texto',
    'renderização-texto',
    'deslocamento-texto-sublinhado',
    'toque-tela',
    'selecao-usuario',
    'seleção-usuario',
    'visibilidade',
    'ao-mudar',
    'indice-z',
    'índice-z',
];

/*

VALORES DE STATUS

auto
none
always
avoid
all
both
left
right

*/