export const ValorQuantificador: { [indice: number]: string } = {
    0: 'atraso-animacao',
    1: 'atraso-animação',
    2: 'duracao-animacao',
    3: 'duração-animação',
    4: 'posicao-horizontal-fundo',
    5: 'posição-horizontal-fundo',
    6: 'posicao-vertical-fundo',
    7: 'posição-vertical-fundo',
    8: 'tamanho-fundo',
    9: 'tamanho-em-bloco',
    10: 'largura-fim-borda-em-bloco',
    11: 'largura-inicio-borda-em-bloco',
    12: 'largura-início-borda-em-bloco',
    13: 'largura-borda-em-bloco',
    14: 'raio-esquerdo-borda-inferior',
    15: 'raio-direito-borda-inferior',
    16: 'largura-borda-inferior',
    17: 'estender-borda-imagem',
    18: 'largura-imagem-borda',
    19: 'largura-fim-borda-em-linha',
    20: 'largura-inicio-borda-em-linha',
    21: 'largura-borda-em-linha',
    22: 'largura-borda-esquerda',
    23: 'raio-borda',
    24: 'largura-borda-direita',
    25: 'espaco-borda',
    26: 'espaço-borda',
    27: 'raio-esquerdo-borda-superior',
    28: 'raio-direito-borda-superior',
    29: 'largura-borda-superior',
    30: 'posicao-inferior',
    31: 'espacamento-coluna',
    32: 'espaçamento-coluna',
    33: 'regras-largura-coluna',
    34: 'largura-coluna',
    35: 'flex-comprimento',
    36: 'tamanho-fonte',
    37: 'esticar-fonte',
    38: 'espacamento',
    39: 'espaçamento',
    40: 'tamanho-colunas-em-grade',
    41: 'tamanho-linhas-em-grade',
    42: 'altura',
    43: 'tamanho-em-linha',
    44: 'insercao',
    45: 'inserção',
    46: 'insercao-em-bloco',
    47: 'inserção-em-bloco',
    48: 'insercao-em-bloco-fim',
    49: 'inserção-em-bloco-fim',
    50: 'inicio-insercao-em-bloco',
    51: 'início-inserção-em-bloco',
    52: 'insercao-em-linha',
    53: 'inserção-em-linha',
    54: 'insercao-em-linha-fim',
    55: 'inserção-em-linha-fim',
    56: 'inicio-insercao-em-linha',
    57: 'início-inserção-em-linha',
    58: 'posicao-esquerda',
    59: 'posição-esquerda',
    60: 'espacamento-letras',
    61: 'espaçamento-letras',
    62: 'altura-linha',
    63: 'margem',
    64: 'margem-em-bloco',
    65: 'margem-em-bloco-fim',
    66: 'inicio-margem-em-bloco',
    67: 'início-margem-em-bloco',
    68: 'margem-inferior',
    69: 'margem-em-linha',
    70: 'margem-em-linha-fim',
    71: 'inicio-margem-em-linha',
    72: 'início-margem-em-linha',
    73: 'margem-esquerda',
    74: 'margem-direita',
    75: 'margem-superior',
    76: 'inicio-borda-mascara',
    77: 'início-borda-máscara',
    78: 'fatiar-borda-mascara',
    79: 'fatiar-borda-máscara',
    80: 'largura-borda-mascara',
    81: 'largura-borda-máscara',
    82: 'tamanho-mascara',
    83: 'tamanho-máscara',
    84: 'altura-maxima',
    85: 'altura-máxima',
    86: 'largura-maxima',
    87: 'largura-máxima',
    88: 'tamanho-maximo-em-bloco',
    89: 'tamanho-máximo-em-bloco',
    90: 'tamanho-maximo-em-linha',
    91: 'tamanho-máximo-em-linha',
    92: 'altura-minima',
    93: 'altura-mínima',
    94: 'largura-minima',
    95: 'largura-mínima',
    96: 'tamanho-minimo-em-bloco',
    97: 'tamanho-mínimo-em-bloco',
    98: 'tamanho-minimo-em-linha',
    99: 'tamanho-mínimo-em-linha',
    100: 'distancia-deslocamento',
    101: 'distância-deslocamento',
    102: 'deslocar-contorno',
    103: 'largura-contorno',
    104: 'recortar-margem-vazada',
    105: 'recuo',
    106: 'recuo-em-bloco',
    107: 'recuo-em-bloco-fim',
    108: 'inicio-recuo-em-bloco',
    109: 'início-recuo-em-bloco',
    110: 'recuo-inferior',
    111: 'recuo-em-linha',
    112: 'recuo-em-linha-fim',
    113: 'inicio-recuo-em-linha',
    114: 'início-recuo-em-linha',
    115: 'recuo-esquerdo',
    116: 'recuo-direito',
    117: 'recuo-superior',
    118: 'perspectiva',
    119: 'origem-perspectiva',
    120: 'posicao-direita',
    121: 'posição-direita',
    122: 'espacamento-linhas',
    123: 'espaçamento-linhas',
    124: 'escala',
    125: 'margem-rolagem-mouse',
    126: 'margem-em-bloco-rolagem-mouse',
    127: 'margem-inferior-rolagem-mouse',
    128: 'margem-em-linha-rolagem-mouse',
    129: 'margem-esquerda-rolagem-mouse',
    130: 'margem-direita-rolagem-mouse',
    131: 'margem-superior-rolagem-mouse',
    132: 'recuo-rolagem-mouse',
    133: 'recuo-em-bloco-rolagem-mouse',
    134: 'recuo-inferior-rolagem-mouse',
    135: 'recuo-em-linha-rolagem-mouse',
    136: 'recuo-esquerdo-rolagem-mouse',
    137: 'recuo-direito-rolagem-mouse',
    138: 'recuo-superior-rolagem-mouse',
    139: 'recuo-esquerdo-rolagem-mouse',
    140: 'recuo-direito-rolagem-mouse',
    141: 'recuo-superior-rolagem-mouse',
    142: 'forma-margem',
    143: 'tabulacao',
    144: 'tabulação',
    145: 'decoracao-espessura-texto',
    146: 'decoração-espessura-texto',
    147: 'indentacao-texto',
    148: 'indentação-texto',
    149: 'deslocamento-texto-sublinhado',
    150: 'posicao-superior',
    151: 'posição-superior',
    152: 'transformar-origem',
    153: 'coordenadas',
    154: 'alinhar-vertical',
    155: 'largura',
    156: 'espacamento-palavras',
    157: 'espaçamento-palavras',
}


/*

VALOR-QUANTIFICADOR: EXEMPLOS

12px
12mm
12em
12cm
12in
12pt
12pc
12ex
12ch
12rem
12vw
12vh
12vmin
12vmax

*/