export const ListaDePosições: { [valorFolEs: string]: string } = {
    "inicio": "start",
    "início": "start",
    "fim": "end",
    "normal": "normal",
    "esticar": "stretch",
    "centro": "center",
    "linha-de-base": "baseline",
    "flex-inicio": "flex-start",
    "flex-início": "flex-start",
    "flex-fim": "flex-end",
    "superior": "top",
    "inferior": "bottom",
    "direita": "right",
    "esquerda": "left",
}
