export const StatusAuto: Array<string> = [
    'aparencia',
    'aparência',
    'proporcao-tela',
    'proporção-tela',
    'tamanho-em-bloco',
    'quebrar-apos',
    'quebrar-após',
    'quebrar-antes',
    'quebrar-dentro',
    'visibilidade-conteudo',
    'visibilidade-conteúdo',
    'espacamento-fonte',
    'espaçamento-fonte',
    'hifens',
    'hífens',
    'isolamento',
    'deslocamento-em-ancora',
    'deslocamento-em-âncora',
    'vazamento-em-ancora',
    'vazamento-em-âncora',
    'vazamento-em-bloco',
    'vazamento-em-linha',
    'vazamento-horizontal',
    'vazamento-vertical',
    'comportamento-rolagem-mouse',
    'comportamento-em-bloco-rolagem-mouse',
    'comportamento-em-linha-rolagem-mouse',
    'comportamento-horizontal-rolagem-mouse',
    'comportamento-vertical-rolagem-mouse',
    'quebrar-pagina-apos',
    'quebrar-página-após',
    'quebrar-pagina-antes',
    'quebrar-página-antes',
    'quebrar-pagina-dentro',
    'quebrar-página-dentro',
    'eventos-ponteiro',
    'comportamento-rolagem',
    'calha-barra-rolagem',
    'largura-barra-rolagem',
    'design-tabela',
    'decoracao-texto-sublinhado',
    'decoração-texto-sublinhado',
    'justificar-texto',
    'renderizacao-texto',
    'renderização-texto',
    'deslocamento-texto-sublinhado',
    'toque-tela',
    'selecao-usuario',
    'seleção-usuario',
    'ao-mudar',
    'indice-z',
    'índice-z',
    'vazamento'
];

export const StatusNenhum: Array<string> = [
    'modo-preenchimento-animacao',
    'modo-preenchimento-animação',
    'fluxo',
    'flutuar',
    'deslocar-pontuacao',
    'deslocar-pontuação',
    'espacamento-fonte',
    'espaçamento-fonte',
    'comportamento-rolagem-mouse',
    'comportamento-em-bloco-rolagem-mouse',
    'comportamento-em-linha-rolagem-mouse',
    'comportamento-horizontal-rolagem-mouse',
    'comportamento-vertical-rolagem-mouse',
    'eventos-ponteiro',
    'citacoes',
    'citações',
    'largura-barra-rolagem',
    'decoracao-texto-sublinhado',
    'decoração-texto-sublinhado',
    'justificar-texto',
    'toque-tela',
    'selecao-usuario',
    'seleção-usuario',
    'imagem-fundo',
    'filtro-fundo',
    'modelo-geral-em-grade',
    'transformar',
];

export const StatusNormal: Array<string> = [
    'agrupar-palavra',
    'direcao-animacao',
    'direção-animação',
    'esquema-cor',
    'espacamento-fonte',
    'espaçamento-fonte',
    'animacao',
    'animação',
    'recursos-fonte',
    'substituir-idioma-fonte',
];

/*

VALORES DE STATUS

auto
none
always
avoid
all
both
left
right

*/