export default {
    ATRIBUTO: "ATRIBUTO",
    CERQUILHA: "CERQUILHA",
    CHAVE_DIREITA: "CHAVE_DIREITA",
    CHAVE_ESQUERDA: "CHAVE_ESQUERDA",
    CLASSE: "CLASSE",
    COLCHETE_DIREITO: "COLCHETE_DIREITO",
    COLCHETE_ESQUERDO: "COLCHETE_ESQUERDO",
    DOIS_PONTOS: "DOIS_PONTOS",
    ESTRUTURA: "ESTRUTURA",
    IDENTIFICADOR: "IDENTIFICADOR",
    MAIOR: "MAIOR",
    NUMERO: "NUMERO",
    PERCENTUAL: "PERCENTUAL",
    PONTO: "PONTO",
    PONTO_E_VIRGULA: "PONTO_E_VIRGULA",
    QUANTIFICADOR: "QUANTIFICADOR",
    TIL: "TIL"
}