export default {
    ATRIBUTO: "ATRIBUTO",
    CHAVE_DIREITA: "CHAVE_DIREITA",
    CHAVE_ESQUERDA: "CHAVE_ESQUERDA",
    CLASSE: "CLASSE",
    COLCHETE_DIREITO: "COLCHETE_DIREITO",
    COLCHETE_ESQUERDO: "COLCHETE_ESQUERDO",
    DOIS_PONTOS: "DOIS_PONTOS",
    ESTRUTURA: "ESTRUTURA",
    IDENTIFICADOR: "IDENTIFICADOR",
    NUMERO: "NUMERO",
    PONTO_E_VIRGULA: "PONTO_E_VIRGULA"
}