name: Testes - Cobertura

on:
  pull_request:
    branches: [ principal ]

jobs:
  testes-unitarios:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: yarn install --frozen-lockfile
    - name: Roda testes e gera relatorio de cobertura
      run: yarn testes-unitarios --ci --json --testLocationInResults --outputFile=report.json
    - name: Salva numero da PR
      if: always()
      run: echo "${{ github.event.pull_request.number }}" > pr-number.txt
    - name: Envia relatorio como artefato
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-cobertura
        path: |
          report.json
          pr-number.txt
        retention-days: 1
